baseURL = '/'
languageCode = 'en-us'
title = 'fipso.dev blog'
theme = 'archie'
copyright = "© fipso"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableRobotsTXT = true

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
  Description = "My personal coding blog where I write about cool stuff"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/fipso"

# Main menu Items
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
